In [2]:
pip install combss

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import combss

In [6]:
# Instantiating an instance of the combss class
optimiser = combss.linear.model()

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

# Parameters
n_samples = 200      # total number of samples
n_features = 30      # total number of predictors
n_informative = 5    # number of non-zero coefficients
noise_std = 1.0      # standard deviation of noise

# Simulate sparse beta (true coefficients)
np.random.seed(0)
beta_true = np.zeros(n_features)
nonzero_idx = np.random.choice(n_features, n_informative, replace=False)
beta_true[nonzero_idx] = np.random.randn(n_informative)

# Generate X and y
X = np.random.randn(n_samples, n_features)
y = X @ beta_true + np.random.randn(n_samples) * noise_std

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: display shape
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")


X_train shape: (140, 30), y_train shape: (140,)
X_test shape: (60, 30), y_test shape: (60,)


In [8]:
beta_true

array([ 0.        ,  0.        ,  1.41437719,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.22988654,  0.        ,  0.        ,  2.00815709,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.60489373,  0.        , -0.12405066,  0.        ])

In [9]:
# A sample usage of the commonly used arguments
optimiser.fit(X_train=X_train, y_train=y_train, X_test=X_test, y_test=y_test, q=8, nlam=20, scaling=True)

Fitting the model ...
Fitting is complete


In [11]:
optimiser.coef_

array([0.        , 0.        , 1.3778326 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 2.07302232, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.63195227, 0.        , 0.        , 0.        ])

In [13]:
optimiser.lambda_

0.007852924866585153

In [15]:
optimiser.lambda_list

[8.041395063383197,
 4.0206975316915985,
 2.0103487658457992,
 1.0051743829228996,
 0.5025871914614498,
 0.2512935957307249,
 0.12564679786536245,
 0.1177938729987773,
 0.09423509839902183,
 0.047117549199510916,
 0.04319108676621834,
 0.10994094813219214,
 0.06282339893268123,
 0.011779387299877729,
 0.009816156083231442,
 0.03926462433292577,
 0.015705849733170307,
 0.03141169946634061,
 0.007852924866585153,
 0.008834540474908299,
 0.00932534827906987]

In [16]:
# A sample usage of the commonly used arguments
optimiser.fit(X_train=X_train, y_train=y_train, X_test=X_test, y_test=y_test, q = 8, nlam = 20, scaling=True)

Fitting the model ...
Fitting is complete


In [17]:
optimiser.subset

array([ 2, 13, 26], dtype=int64)

In [18]:
optimiser.mse

1.4327512803436797

In [19]:
optimiser.coef_

array([0.        , 0.        , 1.3778326 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 2.07302232, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.63195227, 0.        , 0.        , 0.        ])

In [20]:
optimiser.lambda_

0.007852924866585153

In [21]:
optimiser.run_time

4.109375

In [22]:
optimiser.lambda_list

[8.041395063383197,
 4.0206975316915985,
 2.0103487658457992,
 1.0051743829228996,
 0.5025871914614498,
 0.2512935957307249,
 0.12564679786536245,
 0.1177938729987773,
 0.09423509839902183,
 0.047117549199510916,
 0.04319108676621834,
 0.10994094813219214,
 0.06282339893268123,
 0.011779387299877729,
 0.009816156083231442,
 0.03926462433292577,
 0.015705849733170307,
 0.03141169946634061,
 0.007852924866585153,
 0.008834540474908299,
 0.00932534827906987]

In [23]:
optimiser.subset_list

[array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([13], dtype=int64),
 array([13], dtype=int64),
 array([13], dtype=int64),
 array([13], dtype=int64),
 array([13], dtype=int64),
 array([ 2, 13], dtype=int64),
 array([ 2, 13], dtype=int64),
 array([ 2, 13], dtype=int64),
 array([ 2, 13], dtype=int64),
 array([ 2, 13], dtype=int64),
 array([ 2, 13, 26], dtype=int64),
 array([ 2, 13, 26], dtype=int64),
 array([ 2, 13, 26], dtype=int64)]